### ISSUE TITLE
Got Segmentation fault (core dumped)?

### ISSUE THREAD

**Issue by annachen368** [sudouser2010/halfwaytree#1]
I believe pygraphviz has installed.

Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import pygraphviz
> > > exit()

However, when I issue the command, I got "Segmentation fault (core dumped)"

anna@ubuntu:~/HadoopStreamingTester/hadoop-2.7.1/python/halfwaytree$ python example.py 
Segmentation fault (core dumped)

**Comment by sudouser2010** [comment]
Hi Anna, try this:
reinstall Pygraphviz with "sudo pip install pygraphviz"
and try again.

I'm planning to refactor the code this weekend and make it easier to install and use. I think I'll use docker container.

**Comment by annachen368** [comment]
Thanks!
